version: '3.8'

services:
  # RocketMQ NameServer
  namesrv:
    image: apache/rocketmq:5.1.4
    container_name: rmqnamesrv
    network_mode: host
    command: sh mqnamesrv
    environment:
      - JAVA_OPT_EXT=-Xms256m -Xmx256m

  # RocketMQ Broker
  broker:
    image: apache/rocketmq:5.1.4
    container_name: rmqbroker
    network_mode: host
    command: sh mqbroker -n localhost:9876 -c /opt/rocketmq-5.1.4/conf/broker.conf
    environment:
      - JAVA_OPT_EXT=-Xms512m -Xmx512m
    volumes:
      - ./broker.conf:/opt/rocketmq-5.1.4/conf/broker.conf
    depends_on:
      - namesrv

  # RocketMQ Dashboard (管理界面)
  dashboard:
    image: apacherocketmq/rocketmq-dashboard:latest
    container_name: rmqdashboard
    network_mode: host
    environment:
      - JAVA_OPTS=-Drocketmq.namesrv.addr=localhost:9876
    depends_on:
      - namesrv
      - broker


