version: '3.8'
services:
  namesrv:
    image: apache/rocketmq:5.1.0
    container_name: rmqnamesrv
    ports:
      - "9876:9876"
    command: sh mqnamesrv
    volumes:
      - ./data/namesrv/logs:/home/rocketmq/logs
    environment:
      - "MAX_POSSIBLE_HEAP=100000000"

  broker:
    image: apache/rocketmq:5.1.0
    container_name: rmqbroker
    ports:
      - "10911:10911"
    command: sh mqbroker -n namesrv:9876 -c /home/rocketmq/broker.conf
    volumes:
      - ./data/broker/logs:/home/rocketmq/logs
      - ./broker/broker.conf:/home/rocketmq/broker.conf
    environment:
      - "MAX_POSSIBLE_HEAP=200000000"
    depends_on:
      - namesrv

  dashboard:
    image: apacherocketmq/rocketmq-dashboard:latest
    container_name: rmqdashboard
    ports:
      - "8080:8080"
    environment:
      - NAMESRV_ADDR=namesrv:9876
    depends_on:
      - namesrv
      - broker
