// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function ClearHistory():Promise<void>;

export function CreateConnection(arg1:types.ConnectionConfig):Promise<void>;

export function CreateTemplate(arg1:string,arg2:string):Promise<types.MessageTemplate>;

export function CreateTopic(arg1:types.CreateTopicRequest):Promise<void>;

export function DeleteConnection(arg1:string):Promise<void>;

export function DeleteTemplate(arg1:string):Promise<void>;

export function DeleteTopic(arg1:types.DeleteTopicRequest):Promise<void>;

export function GetConnections():Promise<Array<types.ConnectionConfig>>;

export function GetHistory(arg1:number,arg2:number):Promise<Array<types.HistoryRecord>>;

export function GetLogs():Promise<Array<types.LogEntry>>;

export function ListTemplates():Promise<Array<types.MessageTemplate>>;

export function ListTopics(arg1:string):Promise<Array<types.TopicInfo>>;

export function ProduceMessage(arg1:types.ProduceRequest):Promise<void>;

export function SaveFile(arg1:string,arg2:string):Promise<string>;

export function StartConsuming(arg1:types.ConsumeRequest):Promise<string>;

export function StopConsuming(arg1:string):Promise<void>;

export function TestConnection(arg1:string):Promise<types.TestResult>;

export function UpdateConnection(arg1:types.ConnectionConfig):Promise<void>;

export function UpdateTemplate(arg1:string,arg2:string,arg3:string):Promise<void>;
