// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function CreateConnection(arg1) {
  return window['go']['main']['App']['CreateConnection'](arg1);
}

export function CreateTemplate(arg1, arg2) {
  return window['go']['main']['App']['CreateTemplate'](arg1, arg2);
}

export function CreateTopic(arg1) {
  return window['go']['main']['App']['CreateTopic'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DeleteTemplate(arg1) {
  return window['go']['main']['App']['DeleteTemplate'](arg1);
}

export function DeleteTopic(arg1) {
  return window['go']['main']['App']['DeleteTopic'](arg1);
}

export function GetConnections() {
  return window['go']['main']['App']['GetConnections']();
}

export function GetHistory(arg1, arg2) {
  return window['go']['main']['App']['GetHistory'](arg1, arg2);
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function ListTemplates() {
  return window['go']['main']['App']['ListTemplates']();
}

export function ListTopics(arg1) {
  return window['go']['main']['App']['ListTopics'](arg1);
}

export function ProduceMessage(arg1) {
  return window['go']['main']['App']['ProduceMessage'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function StartConsuming(arg1) {
  return window['go']['main']['App']['StartConsuming'](arg1);
}

export function StopConsuming(arg1) {
  return window['go']['main']['App']['StopConsuming'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function UpdateConnection(arg1) {
  return window['go']['main']['App']['UpdateConnection'](arg1);
}

export function UpdateTemplate(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateTemplate'](arg1, arg2, arg3);
}
